name: causal_py312
channels:
  - conda-forge
  - defaults
dependencies:
  - nbmake
  - python=3.12
  - pip
  - numpy>=1.26.0
  - pandas>=2.1.3
  - matplotlib>=3.8.2
  - seaborn>=0.13.0
  - scipy>=1.11.3
  - scikit-learn>=1.3.2
  - statsmodels>=0.14.0
  - networkx>=3.2.1
  - graphviz>=0.20.1
  - ipykernel>=6.27.1
  - jupyter>=1.0.0
  - notebook>=7.0.6
  - pytest>=7.4.3
  - nbformat>=5.9.2
  - pip:
    - nbconvert>=7.11.0